### ISSUE TITLE
Delete doesn't work?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/examples-todomvc#1]
Seems that the item remains there after clicking delete

**Comment by back2dos** [comment]
This was indeed broken, due to coconut.data's inability to reset fields to `null` (but the empty list is null also). I fixed it [a few days ago](https://github.com/MVCoconut/coconut.data/commit/0a38a12b2957d3acea610f7d267c275d462a2ec8) though. Is your checkout of this project up to date?

**Comment by kevinresol** [comment]
> Is your checkout of this project up to date?

Oh well, obvious no :smile:
