### ISSUE TITLE
installation as per instructions fails

### ISSUE THREAD

**Issue by ousado** [MVCoconut/examples-todomvc#2]
.. with "Error: invalid value scoped for resolveLibs in [..]/example-todomvc2/.haxerc" 

After removing switchx, and changing to recent versions for lix and haxeshim it works. What's a bit confusing is that the npm documentation for lix still advises to use switchx

**Comment by back2dos** [comment]
Thanks for the pointer. And sorry, it was all a bit outdated. Lix is here now: https://www.npmjs.com/package/lix ... I should probably deprecate the other one. Works now (at least on travis).
