### ISSUE TITLE
is missing npm run dev ?

### ISSUE THREAD

**Issue by sonygod** [MVCoconut/examples-todomvc#4]
$ haxe todomvc.hxml

unknown variable HAXE_LIBCACHE //what's wrong here?

there are nothing build in bin folder?

is missing npm run dev ?

after run haxe todomvc.hxml

there are no npm run dev like Vue?

**Comment by kevinresol** [comment]
what is your lix version?

**Comment by sonygod** [comment]
lix -v
0.14.0

**Comment by kevinresol** [comment]
Please update to latest.
